--------------------------------------------------------
-- Archivo creado  - sábado-mayo-25-2019
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADDRESS_LAB
--------------------------------------------------------

  CREATE TABLE "C##STUDENT"."ADDRESS_LAB"
   (	"ADDRESS_LAB_ID" NUMBER,
	"CONTACT_LAB_ID" NUMBER,
	"ADDRESS_TYPE" NUMBER,
	"CITY" VARCHAR2(30 BYTE),
	"STATE_PROVINCE" VARCHAR2(30 BYTE),
	"POSTAL_CODE" VARCHAR2(20 BYTE),
	"CREATED_BY" NUMBER,
	"CREATION_DATE" DATE,
	"LAST_UPDATED_BY" NUMBER,
	"LAST_UPDATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMON_LOOKUP_LAB
--------------------------------------------------------

  CREATE TABLE "C##STUDENT"."COMMON_LOOKUP_LAB"
   (	"COMMON_LOOKUP_LAB_ID" NUMBER,
	"COMMON_LOOKUP_CONTEXT" VARCHAR2(30 BYTE),
	"COMMON_LOOKUP_TYPE" VARCHAR2(30 BYTE),
	"COMMON_LOOKUP_MEANING" VARCHAR2(30 BYTE),
	"CREATED_BY" NUMBER,
	"CREATION_DATE" DATE,
	"LAST_UPDATED_BY" NUMBER,
	"LAST_UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONTACT_LAB
--------------------------------------------------------

  CREATE TABLE "C##STUDENT"."CONTACT_LAB"
   (	"CONTACT_LAB_ID" NUMBER,
	"MEMBER_LAB_ID" NUMBER,
	"CONTACT_TYPE" NUMBER,
	"FIRST_NAME" VARCHAR2(20 BYTE),
	"MIDDLE_NAME" VARCHAR2(20 BYTE),
	"LAST_NAME" VARCHAR2(20 BYTE),
	"CREATED_BY" NUMBER,
	"CREATION_DATE" DATE,
	"LAST_UPDATED_BY" NUMBER,
	"LAST_UPDATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITEM_LAB
--------------------------------------------------------

  CREATE TABLE "C##STUDENT"."ITEM_LAB"
   (	"ITEM_LAB_ID" NUMBER,
	"ITEM_BARCODE" VARCHAR2(14 BYTE),
	"ITEM_TYPE" NUMBER,
	"ITEM_TITLE" VARCHAR2(60 BYTE),
	"ITEM_SUBTITLE" VARCHAR2(60 BYTE),
	"ITEM_RATING" VARCHAR2(8 BYTE),
	"ITEM_RELEASE_DATE" DATE,
	"CREATED_BY" NUMBER,
	"CREATION_DATE" DATE,
	"LAST_UPDATED_BY" NUMBER,
	"LAST_UPDATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER_LAB
--------------------------------------------------------

  CREATE TABLE "C##STUDENT"."MEMBER_LAB"
   (	"MEMBER_LAB_ID" NUMBER,
	"MEMBER_TYPE" NUMBER,
	"ACCOUNT_NUMBER" VARCHAR2(10 BYTE),
	"CREDIT_CARD_NUMBER" VARCHAR2(19 BYTE),
	"CREDIT_CARD_TYPE" NUMBER,
	"CREATED_BY" NUMBER,
	"CREATION_DATE" DATE,
	"LAST_UPDATED_BY" NUMBER,
	"LAST_UPDATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RENTAL_ITEM_LAB
--------------------------------------------------------

  CREATE TABLE "C##STUDENT"."RENTAL_ITEM_LAB"
   (	"RENTAL_ITEM_LAB_ID" NUMBER,
	"RENTAL_LAB_ID" NUMBER,
	"ITEM_LAB_ID" NUMBER,
	"CREATED_BY" NUMBER,
	"CREATION_DATE" DATE,
	"LAST_UPDATED_BY" NUMBER,
	"LAST_UPDATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RENTAL_LAB
--------------------------------------------------------

  CREATE TABLE "C##STUDENT"."RENTAL_LAB"
   (	"RENTAL_LAB_ID" NUMBER,
	"CUSTOMER_ID" NUMBER,
	"CHECK_OUT_DATE" DATE,
	"RETURN_DATE" DATE,
	"CREATED_BY" NUMBER,
	"CREATION_DATE" DATE,
	"LAST_UPDATED_BY" NUMBER,
	"LAST_UPDATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STREET_ADDRESS_LAB
--------------------------------------------------------

  CREATE TABLE "C##STUDENT"."STREET_ADDRESS_LAB"
   (	"STREET_ADDRESS_LAB_ID" NUMBER,
	"ADDRESS_LAB_ID" NUMBER,
	"STREET_ADDRESS" VARCHAR2(30 BYTE),
	"CREATED_BY" NUMBER,
	"CREATION_DATE" DATE,
	"LAST_UPDATED_BY" NUMBER,
	"LAST_UPDATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SYSTEM_USER_LAB
--------------------------------------------------------

  CREATE TABLE "C##STUDENT"."SYSTEM_USER_LAB"
   (	"SYSTEM_USER_LAB_ID" NUMBER,
	"SYSTEM_USER_NAME" VARCHAR2(20 BYTE),
	"SYSTEM_USER_GROUP_ID" NUMBER,
	"SYSTEM_USER_TYPE" NUMBER,
	"FIRST_NAME" VARCHAR2(20 BYTE),
	"MIDDLE_NAME" VARCHAR2(20 BYTE),
	"LAST_NAME" VARCHAR2(20 BYTE),
	"CREATED_BY" NUMBER,
	"CREATION_DATE" DATE,
	"LAST_UPDATED_BY" NUMBER,
	"LAST_UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TELEPHONE_LAB
--------------------------------------------------------

  CREATE TABLE "C##STUDENT"."TELEPHONE_LAB"
   (	"TELEPHONE_LAB_ID" NUMBER,
	"CONTACT_LAB_ID" NUMBER,
	"ADDRESS_LAB_ID" NUMBER,
	"TELEPHONE_TYPE" NUMBER,
	"COUNTRY_CODE" VARCHAR2(3 BYTE),
	"AREA_CODE" VARCHAR2(6 BYTE),
	"TELEPHONE_NUMBER" VARCHAR2(10 BYTE),
	"CREATED_BY" NUMBER,
	"CREATION_DATE" DATE,
	"LAST_UPDATED_BY" NUMBER,
	"LAST_UPDATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ADDRESS_LAB_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##STUDENT"."PK_ADDRESS_LAB_1" ON "C##STUDENT"."ADDRESS_LAB" ("ADDRESS_LAB_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADDRESS_LAB_N1
--------------------------------------------------------

  CREATE INDEX "C##STUDENT"."ADDRESS_LAB_N1" ON "C##STUDENT"."ADDRESS_LAB" ("CONTACT_LAB_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADDRESS_LAB_N2
--------------------------------------------------------

  CREATE INDEX "C##STUDENT"."ADDRESS_LAB_N2" ON "C##STUDENT"."ADDRESS_LAB" ("ADDRESS_TYPE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CLOOKUP_LAB_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##STUDENT"."PK_CLOOKUP_LAB_1" ON "C##STUDENT"."COMMON_LOOKUP_LAB" ("COMMON_LOOKUP_LAB_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMMON_LOOKUP_LAB_N1
--------------------------------------------------------

  CREATE INDEX "C##STUDENT"."COMMON_LOOKUP_LAB_N1" ON "C##STUDENT"."COMMON_LOOKUP_LAB" ("COMMON_LOOKUP_CONTEXT")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMMON_LOOKUP_LAB_U2
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##STUDENT"."COMMON_LOOKUP_LAB_U2" ON "C##STUDENT"."COMMON_LOOKUP_LAB" ("COMMON_LOOKUP_CONTEXT", "COMMON_LOOKUP_TYPE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CONTACT_LAB_N1
--------------------------------------------------------

  CREATE INDEX "C##STUDENT"."CONTACT_LAB_N1" ON "C##STUDENT"."CONTACT_LAB" ("MEMBER_LAB_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CONTACT_LAB_N2
--------------------------------------------------------

  CREATE INDEX "C##STUDENT"."CONTACT_LAB_N2" ON "C##STUDENT"."CONTACT_LAB" ("CONTACT_TYPE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CONTACT_LAB_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##STUDENT"."PK_CONTACT_LAB_1" ON "C##STUDENT"."CONTACT_LAB" ("CONTACT_LAB_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ITEM_LAB_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##STUDENT"."PK_ITEM_LAB_1" ON "C##STUDENT"."ITEM_LAB" ("ITEM_LAB_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER_LAB_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##STUDENT"."PK_MEMBER_LAB_1" ON "C##STUDENT"."MEMBER_LAB" ("MEMBER_LAB_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_LAB_N1
--------------------------------------------------------

  CREATE INDEX "C##STUDENT"."MEMBER_LAB_N1" ON "C##STUDENT"."MEMBER_LAB" ("CREDIT_CARD_TYPE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RENTAL_ITEM_LAB_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##STUDENT"."PK_RENTAL_ITEM_LAB_1" ON "C##STUDENT"."RENTAL_ITEM_LAB" ("RENTAL_ITEM_LAB_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RENTAL_LAB_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##STUDENT"."PK_RENTAL_LAB_1" ON "C##STUDENT"."RENTAL_LAB" ("RENTAL_LAB_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_S_ADDRESS_LAB_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##STUDENT"."PK_S_ADDRESS_LAB_1" ON "C##STUDENT"."STREET_ADDRESS_LAB" ("STREET_ADDRESS_LAB_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SYSTEM_USER_LAB_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##STUDENT"."PK_SYSTEM_USER_LAB_1" ON "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_SYSTEM_USER_LAB_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##STUDENT"."UQ_SYSTEM_USER_LAB_1" ON "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TELEPHONE_LAB_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##STUDENT"."PK_TELEPHONE_LAB_1" ON "C##STUDENT"."TELEPHONE_LAB" ("TELEPHONE_LAB_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TELEPHONE_LAB_N1
--------------------------------------------------------

  CREATE INDEX "C##STUDENT"."TELEPHONE_LAB_N1" ON "C##STUDENT"."TELEPHONE_LAB" ("CONTACT_LAB_ID", "ADDRESS_LAB_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TELEPHONE_LAB_N2
--------------------------------------------------------

  CREATE INDEX "C##STUDENT"."TELEPHONE_LAB_N2" ON "C##STUDENT"."TELEPHONE_LAB" ("ADDRESS_LAB_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TELEPHONE_LAB_N3
--------------------------------------------------------

  CREATE INDEX "C##STUDENT"."TELEPHONE_LAB_N3" ON "C##STUDENT"."TELEPHONE_LAB" ("TELEPHONE_TYPE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADDRESS_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."ADDRESS_LAB" MODIFY ("CONTACT_LAB_ID" CONSTRAINT "NN_ADDRESS_LAB_1" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ADDRESS_LAB" MODIFY ("ADDRESS_TYPE" CONSTRAINT "NN_ADDRESS_LAB_2" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ADDRESS_LAB" MODIFY ("CITY" CONSTRAINT "NN_ADDRESS_LAB_3" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ADDRESS_LAB" MODIFY ("STATE_PROVINCE" CONSTRAINT "NN_ADDRESS_LAB_4" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ADDRESS_LAB" MODIFY ("POSTAL_CODE" CONSTRAINT "NN_ADDRESS_LAB_5" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ADDRESS_LAB" MODIFY ("CREATED_BY" CONSTRAINT "NN_ADDRESS_LAB_6" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ADDRESS_LAB" MODIFY ("CREATION_DATE" CONSTRAINT "NN_ADDRESS_LAB_7" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ADDRESS_LAB" MODIFY ("LAST_UPDATED_BY" CONSTRAINT "NN_ADDRESS_LAB_8" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ADDRESS_LAB" MODIFY ("LAST_UPDATE_DATE" CONSTRAINT "NN_ADDRESS_LAB_9" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ADDRESS_LAB" ADD CONSTRAINT "PK_ADDRESS_LAB_1" PRIMARY KEY ("ADDRESS_LAB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMON_LOOKUP_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."COMMON_LOOKUP_LAB" MODIFY ("COMMON_LOOKUP_CONTEXT" CONSTRAINT "NN_CLOOKUP_LAB_1" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."COMMON_LOOKUP_LAB" MODIFY ("COMMON_LOOKUP_TYPE" CONSTRAINT "NN_CLOOKUP_LAB_2" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."COMMON_LOOKUP_LAB" MODIFY ("COMMON_LOOKUP_MEANING" CONSTRAINT "NN_CLOOKUP_LAB_3" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."COMMON_LOOKUP_LAB" MODIFY ("CREATED_BY" CONSTRAINT "NN_CLOOKUP_LAB_4" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."COMMON_LOOKUP_LAB" MODIFY ("CREATION_DATE" CONSTRAINT "NN_CLOOKUP_LAB_5" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."COMMON_LOOKUP_LAB" MODIFY ("LAST_UPDATED_BY" CONSTRAINT "NN_CLOOKUP_LAB_6" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."COMMON_LOOKUP_LAB" MODIFY ("LAST_UPDATE_DATE" CONSTRAINT "NN_CLOOKUP_LAB_7" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."COMMON_LOOKUP_LAB" ADD CONSTRAINT "PK_CLOOKUP_LAB_1" PRIMARY KEY ("COMMON_LOOKUP_LAB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTACT_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."CONTACT_LAB" MODIFY ("MEMBER_LAB_ID" CONSTRAINT "NN_CONTACT_LAB_1" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."CONTACT_LAB" MODIFY ("CONTACT_TYPE" CONSTRAINT "NN_CONTACT_LAB_2" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."CONTACT_LAB" MODIFY ("FIRST_NAME" CONSTRAINT "NN_CONTACT_LAB_3" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."CONTACT_LAB" MODIFY ("LAST_NAME" CONSTRAINT "NN_CONTACT_LAB_4" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."CONTACT_LAB" MODIFY ("CREATED_BY" CONSTRAINT "NN_CONTACT_LAB_5" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."CONTACT_LAB" MODIFY ("CREATION_DATE" CONSTRAINT "NN_CONTACT_LAB_6" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."CONTACT_LAB" MODIFY ("LAST_UPDATED_BY" CONSTRAINT "NN_CONTACT_LAB_7" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."CONTACT_LAB" MODIFY ("LAST_UPDATE_DATE" CONSTRAINT "NN_CONTACT_LAB_8" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."CONTACT_LAB" ADD CONSTRAINT "PK_CONTACT_LAB_1" PRIMARY KEY ("CONTACT_LAB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ITEM_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."ITEM_LAB" MODIFY ("ITEM_BARCODE" CONSTRAINT "NN_ITEM_LAB_1" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ITEM_LAB" MODIFY ("ITEM_TYPE" CONSTRAINT "NN_ITEM_LAB_2" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ITEM_LAB" MODIFY ("ITEM_TITLE" CONSTRAINT "NN_ITEM_LAB_3" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ITEM_LAB" MODIFY ("ITEM_RATING" CONSTRAINT "NN_ITEM_LAB_4" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ITEM_LAB" MODIFY ("ITEM_RELEASE_DATE" CONSTRAINT "NN_ITEM_LAB_5" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ITEM_LAB" MODIFY ("CREATED_BY" CONSTRAINT "NN_ITEM_LAB_6" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ITEM_LAB" MODIFY ("CREATION_DATE" CONSTRAINT "NN_ITEM_LAB_7" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ITEM_LAB" MODIFY ("LAST_UPDATED_BY" CONSTRAINT "NN_ITEM_LAB_8" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ITEM_LAB" MODIFY ("LAST_UPDATE_DATE" CONSTRAINT "NN_ITEM_LAB_9" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."ITEM_LAB" ADD CONSTRAINT "PK_ITEM_LAB_1" PRIMARY KEY ("ITEM_LAB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."MEMBER_LAB" MODIFY ("ACCOUNT_NUMBER" CONSTRAINT "NN_MEMBER_LAB_2" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."MEMBER_LAB" MODIFY ("CREDIT_CARD_NUMBER" CONSTRAINT "NN_MEMBER_LAB_3" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."MEMBER_LAB" MODIFY ("CREDIT_CARD_TYPE" CONSTRAINT "NN_MEMBER_LAB_4" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."MEMBER_LAB" MODIFY ("CREATED_BY" CONSTRAINT "NN_MEMBER_LAB_5" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."MEMBER_LAB" MODIFY ("CREATION_DATE" CONSTRAINT "NN_MEMBER_LAB_6" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."MEMBER_LAB" MODIFY ("LAST_UPDATED_BY" CONSTRAINT "NN_MEMBER_LAB_7" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."MEMBER_LAB" MODIFY ("LAST_UPDATE_DATE" CONSTRAINT "NN_MEMBER_LAB_8" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."MEMBER_LAB" ADD CONSTRAINT "PK_MEMBER_LAB_1" PRIMARY KEY ("MEMBER_LAB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RENTAL_ITEM_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."RENTAL_ITEM_LAB" MODIFY ("RENTAL_LAB_ID" CONSTRAINT "NN_RENTAL_ITEM_LAB_1" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."RENTAL_ITEM_LAB" MODIFY ("ITEM_LAB_ID" CONSTRAINT "NN_RENTAL_ITEM_LAB_2" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."RENTAL_ITEM_LAB" MODIFY ("CREATED_BY" CONSTRAINT "NN_RENTAL_ITEM_LAB_3" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."RENTAL_ITEM_LAB" MODIFY ("CREATION_DATE" CONSTRAINT "NN_RENTAL_ITEM_LAB_4" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."RENTAL_ITEM_LAB" MODIFY ("LAST_UPDATED_BY" CONSTRAINT "NN_RENTAL_ITEM_LAB_5" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."RENTAL_ITEM_LAB" MODIFY ("LAST_UPDATE_DATE" CONSTRAINT "NN_RENTAL_ITEM_LAB_6" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."RENTAL_ITEM_LAB" ADD CONSTRAINT "PK_RENTAL_ITEM_LAB_1" PRIMARY KEY ("RENTAL_ITEM_LAB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RENTAL_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."RENTAL_LAB" MODIFY ("CUSTOMER_ID" CONSTRAINT "NN_RENTAL_LAB_1" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."RENTAL_LAB" MODIFY ("CHECK_OUT_DATE" CONSTRAINT "NN_RENTAL_LAB_2" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."RENTAL_LAB" MODIFY ("RETURN_DATE" CONSTRAINT "NN_RENTAL_LAB_3" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."RENTAL_LAB" MODIFY ("CREATED_BY" CONSTRAINT "NN_RENTAL_LAB_4" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."RENTAL_LAB" MODIFY ("CREATION_DATE" CONSTRAINT "NN_RENTAL_LAB_5" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."RENTAL_LAB" MODIFY ("LAST_UPDATED_BY" CONSTRAINT "NN_RENTAL_LAB_6" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."RENTAL_LAB" MODIFY ("LAST_UPDATE_DATE" CONSTRAINT "NN_RENTAL_LAB_7" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."RENTAL_LAB" ADD CONSTRAINT "PK_RENTAL_LAB_1" PRIMARY KEY ("RENTAL_LAB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STREET_ADDRESS_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."STREET_ADDRESS_LAB" MODIFY ("ADDRESS_LAB_ID" CONSTRAINT "NN_SADDRESS_LAB_1" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."STREET_ADDRESS_LAB" MODIFY ("STREET_ADDRESS" CONSTRAINT "NN_SADDRESS_LAB_2" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."STREET_ADDRESS_LAB" MODIFY ("CREATED_BY" CONSTRAINT "NN_SADDRESS_LAB_3" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."STREET_ADDRESS_LAB" MODIFY ("CREATION_DATE" CONSTRAINT "NN_SADDRESS_LAB_4" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."STREET_ADDRESS_LAB" MODIFY ("LAST_UPDATED_BY" CONSTRAINT "NN_SADDRESS_LAB_5" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."STREET_ADDRESS_LAB" MODIFY ("LAST_UPDATE_DATE" CONSTRAINT "NN_SADDRESS_LAB_6" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."STREET_ADDRESS_LAB" ADD CONSTRAINT "PK_S_ADDRESS_LAB_1" PRIMARY KEY ("STREET_ADDRESS_LAB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SYSTEM_USER_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."SYSTEM_USER_LAB" MODIFY ("SYSTEM_USER_NAME" CONSTRAINT "NN_SYSTEM_USER_LAB_1" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."SYSTEM_USER_LAB" MODIFY ("SYSTEM_USER_GROUP_ID" CONSTRAINT "NN_SYSTEM_USER_LAB_2" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."SYSTEM_USER_LAB" MODIFY ("SYSTEM_USER_TYPE" CONSTRAINT "NN_SYSTEM_USER_LAB_3" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."SYSTEM_USER_LAB" MODIFY ("CREATED_BY" CONSTRAINT "NN_SYSTEM_USER_LAB_4" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."SYSTEM_USER_LAB" MODIFY ("CREATION_DATE" CONSTRAINT "NN_SYSTEM_USER_LAB_5" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."SYSTEM_USER_LAB" MODIFY ("LAST_UPDATED_BY" CONSTRAINT "NN_SYSTEM_USER_LAB_6" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."SYSTEM_USER_LAB" MODIFY ("LAST_UPDATE_DATE" CONSTRAINT "NN_SYSTEM_USER_LAB_7" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."SYSTEM_USER_LAB" ADD CONSTRAINT "PK_SYSTEM_USER_LAB_1" PRIMARY KEY ("SYSTEM_USER_LAB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TELEPHONE_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."TELEPHONE_LAB" MODIFY ("CONTACT_LAB_ID" CONSTRAINT "NN_TELEPHONE_LAB_1" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."TELEPHONE_LAB" MODIFY ("TELEPHONE_TYPE" CONSTRAINT "NN_TELEPHONE_LAB_2" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."TELEPHONE_LAB" MODIFY ("COUNTRY_CODE" CONSTRAINT "NN_TELEPHONE_LAB_3" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."TELEPHONE_LAB" MODIFY ("AREA_CODE" CONSTRAINT "NN_TELEPHONE_LAB_4" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."TELEPHONE_LAB" MODIFY ("TELEPHONE_NUMBER" CONSTRAINT "NN_TELEPHONE_LAB_5" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."TELEPHONE_LAB" MODIFY ("CREATED_BY" CONSTRAINT "NN_TELEPHONE_LAB_6" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."TELEPHONE_LAB" MODIFY ("CREATION_DATE" CONSTRAINT "NN_TELEPHONE_LAB_7" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."TELEPHONE_LAB" MODIFY ("LAST_UPDATED_BY" CONSTRAINT "NN_TELEPHONE_LAB_8" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."TELEPHONE_LAB" MODIFY ("LAST_UPDATE_DATE" CONSTRAINT "NN_TELEPHONE_LAB_9" NOT NULL ENABLE);
  ALTER TABLE "C##STUDENT"."TELEPHONE_LAB" ADD CONSTRAINT "PK_TELEPHONE_LAB_1" PRIMARY KEY ("TELEPHONE_LAB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADDRESS_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."ADDRESS_LAB" ADD CONSTRAINT "FK_ADDRESS_LAB_1" FOREIGN KEY ("CONTACT_LAB_ID")
	  REFERENCES "C##STUDENT"."CONTACT_LAB" ("CONTACT_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."ADDRESS_LAB" ADD CONSTRAINT "FK_ADDRESS_LAB_2" FOREIGN KEY ("ADDRESS_TYPE")
	  REFERENCES "C##STUDENT"."COMMON_LOOKUP_LAB" ("COMMON_LOOKUP_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."ADDRESS_LAB" ADD CONSTRAINT "FK_ADDRESS_LAB_3" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."ADDRESS_LAB" ADD CONSTRAINT "FK_ADDRESS_LAB_4" FOREIGN KEY ("LAST_UPDATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMON_LOOKUP_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."COMMON_LOOKUP_LAB" ADD CONSTRAINT "FK_CLOOKUP_LAB_1" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."COMMON_LOOKUP_LAB" ADD CONSTRAINT "FK_CLOOKUP_LAB_2" FOREIGN KEY ("LAST_UPDATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTACT_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."CONTACT_LAB" ADD CONSTRAINT "FK_CONTACT_LAB_1" FOREIGN KEY ("MEMBER_LAB_ID")
	  REFERENCES "C##STUDENT"."MEMBER_LAB" ("MEMBER_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."CONTACT_LAB" ADD CONSTRAINT "FK_CONTACT_LAB_2" FOREIGN KEY ("CONTACT_TYPE")
	  REFERENCES "C##STUDENT"."COMMON_LOOKUP_LAB" ("COMMON_LOOKUP_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."CONTACT_LAB" ADD CONSTRAINT "FK_CONTACT_LAB_3" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."CONTACT_LAB" ADD CONSTRAINT "FK_CONTACT_LAB_4" FOREIGN KEY ("LAST_UPDATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ITEM_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."ITEM_LAB" ADD CONSTRAINT "FK_ITEM_LAB_1" FOREIGN KEY ("ITEM_TYPE")
	  REFERENCES "C##STUDENT"."COMMON_LOOKUP_LAB" ("COMMON_LOOKUP_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."ITEM_LAB" ADD CONSTRAINT "FK_ITEM_LAB_2" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."ITEM_LAB" ADD CONSTRAINT "FK_ITEM_LAB_3" FOREIGN KEY ("LAST_UPDATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMBER_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."MEMBER_LAB" ADD CONSTRAINT "FK_MEMBER_LAB_1" FOREIGN KEY ("MEMBER_TYPE")
	  REFERENCES "C##STUDENT"."COMMON_LOOKUP_LAB" ("COMMON_LOOKUP_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."MEMBER_LAB" ADD CONSTRAINT "FK_MEMBER_LAB_2" FOREIGN KEY ("CREDIT_CARD_TYPE")
	  REFERENCES "C##STUDENT"."COMMON_LOOKUP_LAB" ("COMMON_LOOKUP_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."MEMBER_LAB" ADD CONSTRAINT "FK_MEMBER_LAB_3" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."MEMBER_LAB" ADD CONSTRAINT "FK_MEMBER_LAB_4" FOREIGN KEY ("LAST_UPDATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RENTAL_ITEM_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."RENTAL_ITEM_LAB" ADD CONSTRAINT "FK_RENTAL_ITEM_LAB_1" FOREIGN KEY ("RENTAL_LAB_ID")
	  REFERENCES "C##STUDENT"."RENTAL_LAB" ("RENTAL_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."RENTAL_ITEM_LAB" ADD CONSTRAINT "FK_RENTAL_ITEM_LAB_2" FOREIGN KEY ("ITEM_LAB_ID")
	  REFERENCES "C##STUDENT"."ITEM_LAB" ("ITEM_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."RENTAL_ITEM_LAB" ADD CONSTRAINT "FK_RENTAL_ITEM_LAB_3" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."RENTAL_ITEM_LAB" ADD CONSTRAINT "FK_RENTAL_ITEM_LAB_4" FOREIGN KEY ("LAST_UPDATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RENTAL_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."RENTAL_LAB" ADD CONSTRAINT "FK_RENTAL_LAB_1" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "C##STUDENT"."CONTACT_LAB" ("CONTACT_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."RENTAL_LAB" ADD CONSTRAINT "FK_RENTAL_LAB_2" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."RENTAL_LAB" ADD CONSTRAINT "FK_RENTAL_LAB_3" FOREIGN KEY ("LAST_UPDATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STREET_ADDRESS_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."STREET_ADDRESS_LAB" ADD CONSTRAINT "FK_S_ADDRESS_LAB_1" FOREIGN KEY ("ADDRESS_LAB_ID")
	  REFERENCES "C##STUDENT"."ADDRESS_LAB" ("ADDRESS_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."STREET_ADDRESS_LAB" ADD CONSTRAINT "FK_S_ADDRESS_LAB_3" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."STREET_ADDRESS_LAB" ADD CONSTRAINT "FK_S_ADDRESS_LAB_4" FOREIGN KEY ("LAST_UPDATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SYSTEM_USER_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."SYSTEM_USER_LAB" ADD CONSTRAINT "FK_SYSTEM_USER_LAB_1" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."SYSTEM_USER_LAB" ADD CONSTRAINT "FK_SYSTEM_USER_LAB_2" FOREIGN KEY ("LAST_UPDATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."SYSTEM_USER_LAB" ADD CONSTRAINT "FK_SYSTEM_USER_LAB_3" FOREIGN KEY ("SYSTEM_USER_GROUP_ID")
	  REFERENCES "C##STUDENT"."COMMON_LOOKUP_LAB" ("COMMON_LOOKUP_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."SYSTEM_USER_LAB" ADD CONSTRAINT "FK_SYSTEM_USER_LAB_4" FOREIGN KEY ("SYSTEM_USER_TYPE")
	  REFERENCES "C##STUDENT"."COMMON_LOOKUP_LAB" ("COMMON_LOOKUP_LAB_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TELEPHONE_LAB
--------------------------------------------------------

  ALTER TABLE "C##STUDENT"."TELEPHONE_LAB" ADD CONSTRAINT "FK_TELEPHONE_LAB_1" FOREIGN KEY ("CONTACT_LAB_ID")
	  REFERENCES "C##STUDENT"."CONTACT_LAB" ("CONTACT_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."TELEPHONE_LAB" ADD CONSTRAINT "FK_TELEPHONE_LAB_2" FOREIGN KEY ("TELEPHONE_TYPE")
	  REFERENCES "C##STUDENT"."COMMON_LOOKUP_LAB" ("COMMON_LOOKUP_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."TELEPHONE_LAB" ADD CONSTRAINT "FK_TELEPHONE_LAB_3" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
  ALTER TABLE "C##STUDENT"."TELEPHONE_LAB" ADD CONSTRAINT "FK_TELEPHONE_LAB_4" FOREIGN KEY ("LAST_UPDATED_BY")
	  REFERENCES "C##STUDENT"."SYSTEM_USER_LAB" ("SYSTEM_USER_LAB_ID") ENABLE;
